26 august

hahahaahahah, can't help but laugh at myself for getting stuck for several hours just for a missing pair of "".

so here we go, it turns out I had missed the fact that the object representing the address of the NFt deployed, `oneNftDeployed.address` in the error statement `` const error = `MarsKetplace__AlreadyListed("${oneNftDeployed.address}", ${TOKENID})` ``

I can't explain it yet, I thought the syntax for errors and events would be similar, but it looks like when testing events, "" are not necessary to surround addresses, while in errors, it is necessary for addresses to be enclosed in ""

- tested `yarn hardhat coverage`, and got a total of 66% covered (I was actually expecting less than that!)
